// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/detection/v1/detection.proto

package detectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameRequest contains a video frame to be processed
type FrameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Camera identifier
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Frame sequence number for ordering validation
	FrameSeq uint64 `protobuf:"varint,2,opt,name=frame_seq,json=frameSeq,proto3" json:"frame_seq,omitempty"`
	// Capture timestamp in nanoseconds since epoch
	TimestampNs int64 `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// JPEG-encoded frame data
	JpegData []byte `protobuf:"bytes,4,opt,name=jpeg_data,json=jpegData,proto3" json:"jpeg_data,omitempty"`
	// Request annotated image with bounding boxes drawn
	ReturnAnnotated bool `protobuf:"varint,5,opt,name=return_annotated,json=returnAnnotated,proto3" json:"return_annotated,omitempty"`
	// Minimum confidence threshold for detections (0-1)
	ConfThreshold float32 `protobuf:"fixed32,6,opt,name=conf_threshold,json=confThreshold,proto3" json:"conf_threshold,omitempty"`
	// Enable object tracking (ByteTrack/BoT-SORT)
	EnableTracking bool `protobuf:"varint,7,opt,name=enable_tracking,json=enableTracking,proto3" json:"enable_tracking,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameRequest) GetFrameSeq() uint64 {
	if x != nil {
		return x.FrameSeq
	}
	return 0
}

func (x *FrameRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *FrameRequest) GetJpegData() []byte {
	if x != nil {
		return x.JpegData
	}
	return nil
}

func (x *FrameRequest) GetReturnAnnotated() bool {
	if x != nil {
		return x.ReturnAnnotated
	}
	return false
}

func (x *FrameRequest) GetConfThreshold() float32 {
	if x != nil {
		return x.ConfThreshold
	}
	return 0
}

func (x *FrameRequest) GetEnableTracking() bool {
	if x != nil {
		return x.EnableTracking
	}
	return false
}

// DetectionResponse contains detection results for a processed frame
type DetectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Camera identifier (echoed from request)
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Frame sequence number (echoed from request)
	FrameSeq uint64 `protobuf:"varint,2,opt,name=frame_seq,json=frameSeq,proto3" json:"frame_seq,omitempty"`
	// Original capture timestamp
	CaptureTimestampNs int64 `protobuf:"varint,3,opt,name=capture_timestamp_ns,json=captureTimestampNs,proto3" json:"capture_timestamp_ns,omitempty"`
	// When inference completed
	InferenceTimestampNs int64 `protobuf:"varint,4,opt,name=inference_timestamp_ns,json=inferenceTimestampNs,proto3" json:"inference_timestamp_ns,omitempty"`
	// Detected objects
	Detections []*Detection `protobuf:"bytes,5,rep,name=detections,proto3" json:"detections,omitempty"`
	// Annotated JPEG image with bounding boxes (if requested)
	AnnotatedJpeg []byte `protobuf:"bytes,6,opt,name=annotated_jpeg,json=annotatedJpeg,proto3" json:"annotated_jpeg,omitempty"`
	// Inference time in milliseconds
	InferenceMs float32 `protobuf:"fixed32,7,opt,name=inference_ms,json=inferenceMs,proto3" json:"inference_ms,omitempty"`
	// Device used for inference (cuda, cpu, etc.)
	Device string `protobuf:"bytes,8,opt,name=device,proto3" json:"device,omitempty"`
	// Track updates from ByteTrack/BoT-SORT
	Tracks        []*TrackUpdate `protobuf:"bytes,9,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionResponse) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *DetectionResponse) GetFrameSeq() uint64 {
	if x != nil {
		return x.FrameSeq
	}
	return 0
}

func (x *DetectionResponse) GetCaptureTimestampNs() int64 {
	if x != nil {
		return x.CaptureTimestampNs
	}
	return 0
}

func (x *DetectionResponse) GetInferenceTimestampNs() int64 {
	if x != nil {
		return x.InferenceTimestampNs
	}
	return 0
}

func (x *DetectionResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *DetectionResponse) GetAnnotatedJpeg() []byte {
	if x != nil {
		return x.AnnotatedJpeg
	}
	return nil
}

func (x *DetectionResponse) GetInferenceMs() float32 {
	if x != nil {
		return x.InferenceMs
	}
	return 0
}

func (x *DetectionResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DetectionResponse) GetTracks() []*TrackUpdate {
	if x != nil {
		return x.Tracks
	}
	return nil
}

// Detection represents a single detected object
type Detection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object class name (person, car, etc.)
	ClassName string `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	// Class ID from COCO/custom dataset
	ClassId int32 `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	// Detection confidence (0-1)
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Bounding box coordinates
	Bbox *BBox `protobuf:"bytes,4,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// Track ID from object tracker (0 if not tracked)
	TrackId int32 `protobuf:"varint,5,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	// Velocity in pixels per frame (for latency compensation)
	VelocityX float32 `protobuf:"fixed32,6,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"`
	VelocityY float32 `protobuf:"fixed32,7,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
	// Threat level for security applications
	ThreatLevel   string `protobuf:"bytes,8,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Detection) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *Detection) GetVelocityX() float32 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *Detection) GetVelocityY() float32 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

func (x *Detection) GetThreatLevel() string {
	if x != nil {
		return x.ThreatLevel
	}
	return ""
}

// BBox represents a bounding box
type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"` // Left
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"` // Top
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"` // Right
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"` // Bottom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{3}
}

func (x *BBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BBox) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BBox) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

// TrackUpdate contains tracking information for an object
type TrackUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique track identifier
	TrackId int32 `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	// Track state: new, active, lost, removed
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Associated detection (if any)
	Detection *Detection `protobuf:"bytes,3,opt,name=detection,proto3" json:"detection,omitempty"`
	// Number of frames this track has been active
	Age int32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	// Number of frames since last detection
	TimeSinceUpdate int32 `protobuf:"varint,5,opt,name=time_since_update,json=timeSinceUpdate,proto3" json:"time_since_update,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrackUpdate) Reset() {
	*x = TrackUpdate{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUpdate) ProtoMessage() {}

func (x *TrackUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUpdate.ProtoReflect.Descriptor instead.
func (*TrackUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{4}
}

func (x *TrackUpdate) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *TrackUpdate) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TrackUpdate) GetDetection() *Detection {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *TrackUpdate) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TrackUpdate) GetTimeSinceUpdate() int32 {
	if x != nil {
		return x.TimeSinceUpdate
	}
	return 0
}

// HealthRequest is empty - just checks service availability
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{5}
}

// HealthResponse contains service health status
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service status: healthy, unhealthy, degraded
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Device being used (cuda, cpu, rocm)
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// Whether the model is loaded and ready
	ModelLoaded bool `protobuf:"varint,3,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	// Current tracker type in use
	TrackerType string `protobuf:"bytes,4,opt,name=tracker_type,json=trackerType,proto3" json:"tracker_type,omitempty"`
	// Model name being used
	ModelName string `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Number of active streams
	ActiveStreams int32 `protobuf:"varint,6,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthResponse) GetTrackerType() string {
	if x != nil {
		return x.TrackerType
	}
	return ""
}

func (x *HealthResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HealthResponse) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

// ConfigureRequest updates detection parameters
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confidence threshold (0-1)
	ConfThreshold *float32 `protobuf:"fixed32,1,opt,name=conf_threshold,json=confThreshold,proto3,oneof" json:"conf_threshold,omitempty"`
	// IOU threshold for NMS (0-1)
	IouThreshold *float32 `protobuf:"fixed32,2,opt,name=iou_threshold,json=iouThreshold,proto3,oneof" json:"iou_threshold,omitempty"`
	// Enable/disable tracking
	EnableTracking *bool `protobuf:"varint,3,opt,name=enable_tracking,json=enableTracking,proto3,oneof" json:"enable_tracking,omitempty"`
	// Tracker type: bytetrack, botsort, or empty to disable
	TrackerType *string `protobuf:"bytes,4,opt,name=tracker_type,json=trackerType,proto3,oneof" json:"tracker_type,omitempty"`
	// Classes to detect (empty = all classes)
	Classes       []string `protobuf:"bytes,5,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetConfThreshold() float32 {
	if x != nil && x.ConfThreshold != nil {
		return *x.ConfThreshold
	}
	return 0
}

func (x *ConfigureRequest) GetIouThreshold() float32 {
	if x != nil && x.IouThreshold != nil {
		return *x.IouThreshold
	}
	return 0
}

func (x *ConfigureRequest) GetEnableTracking() bool {
	if x != nil && x.EnableTracking != nil {
		return *x.EnableTracking
	}
	return false
}

func (x *ConfigureRequest) GetTrackerType() string {
	if x != nil && x.TrackerType != nil {
		return *x.TrackerType
	}
	return ""
}

func (x *ConfigureRequest) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

// ConfigureResponse confirms configuration update
type ConfigureResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Current configuration after update
	ConfThreshold   float32 `protobuf:"fixed32,3,opt,name=conf_threshold,json=confThreshold,proto3" json:"conf_threshold,omitempty"`
	IouThreshold    float32 `protobuf:"fixed32,4,opt,name=iou_threshold,json=iouThreshold,proto3" json:"iou_threshold,omitempty"`
	TrackingEnabled bool    `protobuf:"varint,5,opt,name=tracking_enabled,json=trackingEnabled,proto3" json:"tracking_enabled,omitempty"`
	TrackerType     string  `protobuf:"bytes,6,opt,name=tracker_type,json=trackerType,proto3" json:"tracker_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_detection_v1_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_detection_v1_detection_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureResponse) GetConfThreshold() float32 {
	if x != nil {
		return x.ConfThreshold
	}
	return 0
}

func (x *ConfigureResponse) GetIouThreshold() float32 {
	if x != nil {
		return x.IouThreshold
	}
	return 0
}

func (x *ConfigureResponse) GetTrackingEnabled() bool {
	if x != nil {
		return x.TrackingEnabled
	}
	return false
}

func (x *ConfigureResponse) GetTrackerType() string {
	if x != nil {
		return x.TrackerType
	}
	return ""
}

var File_api_proto_detection_v1_detection_proto protoreflect.FileDescriptor

const file_api_proto_detection_v1_detection_proto_rawDesc = "" +
	"\n" +
	"&api/proto/detection/v1/detection.proto\x12\x11orbo.detection.v1\"\x83\x02\n" +
	"\fFrameRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1b\n" +
	"\tframe_seq\x18\x02 \x01(\x04R\bframeSeq\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\tjpeg_data\x18\x04 \x01(\fR\bjpegData\x12)\n" +
	"\x10return_annotated\x18\x05 \x01(\bR\x0freturnAnnotated\x12%\n" +
	"\x0econf_threshold\x18\x06 \x01(\x02R\rconfThreshold\x12'\n" +
	"\x0fenable_tracking\x18\a \x01(\bR\x0eenableTracking\"\x8d\x03\n" +
	"\x11DetectionResponse\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1b\n" +
	"\tframe_seq\x18\x02 \x01(\x04R\bframeSeq\x120\n" +
	"\x14capture_timestamp_ns\x18\x03 \x01(\x03R\x12captureTimestampNs\x124\n" +
	"\x16inference_timestamp_ns\x18\x04 \x01(\x03R\x14inferenceTimestampNs\x12<\n" +
	"\n" +
	"detections\x18\x05 \x03(\v2\x1c.orbo.detection.v1.DetectionR\n" +
	"detections\x12%\n" +
	"\x0eannotated_jpeg\x18\x06 \x01(\fR\rannotatedJpeg\x12!\n" +
	"\finference_ms\x18\a \x01(\x02R\vinferenceMs\x12\x16\n" +
	"\x06device\x18\b \x01(\tR\x06device\x126\n" +
	"\x06tracks\x18\t \x03(\v2\x1e.orbo.detection.v1.TrackUpdateR\x06tracks\"\x8e\x02\n" +
	"\tDetection\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\x05R\aclassId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x04bbox\x18\x04 \x01(\v2\x17.orbo.detection.v1.BBoxR\x04bbox\x12\x19\n" +
	"\btrack_id\x18\x05 \x01(\x05R\atrackId\x12\x1d\n" +
	"\n" +
	"velocity_x\x18\x06 \x01(\x02R\tvelocityX\x12\x1d\n" +
	"\n" +
	"velocity_y\x18\a \x01(\x02R\tvelocityY\x12!\n" +
	"\fthreat_level\x18\b \x01(\tR\vthreatLevel\"F\n" +
	"\x04BBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\"\xb8\x01\n" +
	"\vTrackUpdate\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\x05R\atrackId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12:\n" +
	"\tdetection\x18\x03 \x01(\v2\x1c.orbo.detection.v1.DetectionR\tdetection\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12*\n" +
	"\x11time_since_update\x18\x05 \x01(\x05R\x0ftimeSinceUpdate\"\x0f\n" +
	"\rHealthRequest\"\xcc\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12!\n" +
	"\fmodel_loaded\x18\x03 \x01(\bR\vmodelLoaded\x12!\n" +
	"\ftracker_type\x18\x04 \x01(\tR\vtrackerType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12%\n" +
	"\x0eactive_streams\x18\x06 \x01(\x05R\ractiveStreams\"\xa2\x02\n" +
	"\x10ConfigureRequest\x12*\n" +
	"\x0econf_threshold\x18\x01 \x01(\x02H\x00R\rconfThreshold\x88\x01\x01\x12(\n" +
	"\riou_threshold\x18\x02 \x01(\x02H\x01R\fiouThreshold\x88\x01\x01\x12,\n" +
	"\x0fenable_tracking\x18\x03 \x01(\bH\x02R\x0eenableTracking\x88\x01\x01\x12&\n" +
	"\ftracker_type\x18\x04 \x01(\tH\x03R\vtrackerType\x88\x01\x01\x12\x18\n" +
	"\aclasses\x18\x05 \x03(\tR\aclassesB\x11\n" +
	"\x0f_conf_thresholdB\x10\n" +
	"\x0e_iou_thresholdB\x12\n" +
	"\x10_enable_trackingB\x0f\n" +
	"\r_tracker_type\"\xe1\x01\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0econf_threshold\x18\x03 \x01(\x02R\rconfThreshold\x12#\n" +
	"\riou_threshold\x18\x04 \x01(\x02R\fiouThreshold\x12)\n" +
	"\x10tracking_enabled\x18\x05 \x01(\bR\x0ftrackingEnabled\x12!\n" +
	"\ftracker_type\x18\x06 \x01(\tR\vtrackerType2\x99\x02\n" +
	"\x10DetectionService\x12Y\n" +
	"\fDetectStream\x12\x1f.orbo.detection.v1.FrameRequest\x1a$.orbo.detection.v1.DetectionResponse(\x010\x01\x12R\n" +
	"\vHealthCheck\x12 .orbo.detection.v1.HealthRequest\x1a!.orbo.detection.v1.HealthResponse\x12V\n" +
	"\tConfigure\x12#.orbo.detection.v1.ConfigureRequest\x1a$.orbo.detection.v1.ConfigureResponseB)Z'orbo/api/proto/detection/v1;detectionv1b\x06proto3"

var (
	file_api_proto_detection_v1_detection_proto_rawDescOnce sync.Once
	file_api_proto_detection_v1_detection_proto_rawDescData []byte
)

func file_api_proto_detection_v1_detection_proto_rawDescGZIP() []byte {
	file_api_proto_detection_v1_detection_proto_rawDescOnce.Do(func() {
		file_api_proto_detection_v1_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_detection_v1_detection_proto_rawDesc), len(file_api_proto_detection_v1_detection_proto_rawDesc)))
	})
	return file_api_proto_detection_v1_detection_proto_rawDescData
}

var file_api_proto_detection_v1_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_detection_v1_detection_proto_goTypes = []any{
	(*FrameRequest)(nil),      // 0: orbo.detection.v1.FrameRequest
	(*DetectionResponse)(nil), // 1: orbo.detection.v1.DetectionResponse
	(*Detection)(nil),         // 2: orbo.detection.v1.Detection
	(*BBox)(nil),              // 3: orbo.detection.v1.BBox
	(*TrackUpdate)(nil),       // 4: orbo.detection.v1.TrackUpdate
	(*HealthRequest)(nil),     // 5: orbo.detection.v1.HealthRequest
	(*HealthResponse)(nil),    // 6: orbo.detection.v1.HealthResponse
	(*ConfigureRequest)(nil),  // 7: orbo.detection.v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 8: orbo.detection.v1.ConfigureResponse
}
var file_api_proto_detection_v1_detection_proto_depIdxs = []int32{
	2, // 0: orbo.detection.v1.DetectionResponse.detections:type_name -> orbo.detection.v1.Detection
	4, // 1: orbo.detection.v1.DetectionResponse.tracks:type_name -> orbo.detection.v1.TrackUpdate
	3, // 2: orbo.detection.v1.Detection.bbox:type_name -> orbo.detection.v1.BBox
	2, // 3: orbo.detection.v1.TrackUpdate.detection:type_name -> orbo.detection.v1.Detection
	0, // 4: orbo.detection.v1.DetectionService.DetectStream:input_type -> orbo.detection.v1.FrameRequest
	5, // 5: orbo.detection.v1.DetectionService.HealthCheck:input_type -> orbo.detection.v1.HealthRequest
	7, // 6: orbo.detection.v1.DetectionService.Configure:input_type -> orbo.detection.v1.ConfigureRequest
	1, // 7: orbo.detection.v1.DetectionService.DetectStream:output_type -> orbo.detection.v1.DetectionResponse
	6, // 8: orbo.detection.v1.DetectionService.HealthCheck:output_type -> orbo.detection.v1.HealthResponse
	8, // 9: orbo.detection.v1.DetectionService.Configure:output_type -> orbo.detection.v1.ConfigureResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_detection_v1_detection_proto_init() }
func file_api_proto_detection_v1_detection_proto_init() {
	if File_api_proto_detection_v1_detection_proto != nil {
		return
	}
	file_api_proto_detection_v1_detection_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_detection_v1_detection_proto_rawDesc), len(file_api_proto_detection_v1_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_detection_v1_detection_proto_goTypes,
		DependencyIndexes: file_api_proto_detection_v1_detection_proto_depIdxs,
		MessageInfos:      file_api_proto_detection_v1_detection_proto_msgTypes,
	}.Build()
	File_api_proto_detection_v1_detection_proto = out.File
	file_api_proto_detection_v1_detection_proto_goTypes = nil
	file_api_proto_detection_v1_detection_proto_depIdxs = nil
}
