// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/detection/v1/detection.proto

package detectionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectionService_DetectStream_FullMethodName = "/orbo.detection.v1.DetectionService/DetectStream"
	DetectionService_HealthCheck_FullMethodName  = "/orbo.detection.v1.DetectionService/HealthCheck"
	DetectionService_Configure_FullMethodName    = "/orbo.detection.v1.DetectionService/Configure"
)

// DetectionServiceClient is the client API for DetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DetectionService provides real-time object detection using YOLO
type DetectionServiceClient interface {
	// DetectStream is a bidirectional streaming RPC for real-time detection
	// Client sends frames, server responds with detection results
	DetectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, DetectionResponse], error)
	// HealthCheck verifies the detection service is operational
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Configure updates detection parameters at runtime
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
}

type detectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectionServiceClient(cc grpc.ClientConnInterface) DetectionServiceClient {
	return &detectionServiceClient{cc}
}

func (c *detectionServiceClient) DetectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, DetectionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DetectionService_ServiceDesc.Streams[0], DetectionService_DetectStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, DetectionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DetectionService_DetectStreamClient = grpc.BidiStreamingClient[FrameRequest, DetectionResponse]

func (c *detectionServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DetectionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, DetectionService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectionServiceServer is the server API for DetectionService service.
// All implementations must embed UnimplementedDetectionServiceServer
// for forward compatibility.
//
// DetectionService provides real-time object detection using YOLO
type DetectionServiceServer interface {
	// DetectStream is a bidirectional streaming RPC for real-time detection
	// Client sends frames, server responds with detection results
	DetectStream(grpc.BidiStreamingServer[FrameRequest, DetectionResponse]) error
	// HealthCheck verifies the detection service is operational
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// Configure updates detection parameters at runtime
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	mustEmbedUnimplementedDetectionServiceServer()
}

// UnimplementedDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectionServiceServer struct{}

func (UnimplementedDetectionServiceServer) DetectStream(grpc.BidiStreamingServer[FrameRequest, DetectionResponse]) error {
	return status.Error(codes.Unimplemented, "method DetectStream not implemented")
}
func (UnimplementedDetectionServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDetectionServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedDetectionServiceServer) mustEmbedUnimplementedDetectionServiceServer() {}
func (UnimplementedDetectionServiceServer) testEmbeddedByValue()                          {}

// UnsafeDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectionServiceServer will
// result in compilation errors.
type UnsafeDetectionServiceServer interface {
	mustEmbedUnimplementedDetectionServiceServer()
}

func RegisterDetectionServiceServer(s grpc.ServiceRegistrar, srv DetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectionService_ServiceDesc, srv)
}

func _DetectionService_DetectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DetectionServiceServer).DetectStream(&grpc.GenericServerStream[FrameRequest, DetectionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DetectionService_DetectStreamServer = grpc.BidiStreamingServer[FrameRequest, DetectionResponse]

func _DetectionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectionService_ServiceDesc is the grpc.ServiceDesc for DetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbo.detection.v1.DetectionService",
	HandlerType: (*DetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _DetectionService_HealthCheck_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _DetectionService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectStream",
			Handler:       _DetectionService_DetectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/detection/v1/detection.proto",
}
