// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/recognition/v1/recognition.proto

package recognitionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceRecognitionService_RecognizeStream_FullMethodName = "/orbo.recognition.v1.FaceRecognitionService/RecognizeStream"
	FaceRecognitionService_RegisterFace_FullMethodName    = "/orbo.recognition.v1.FaceRecognitionService/RegisterFace"
	FaceRecognitionService_DeleteFace_FullMethodName      = "/orbo.recognition.v1.FaceRecognitionService/DeleteFace"
	FaceRecognitionService_ListFaces_FullMethodName       = "/orbo.recognition.v1.FaceRecognitionService/ListFaces"
	FaceRecognitionService_HealthCheck_FullMethodName     = "/orbo.recognition.v1.FaceRecognitionService/HealthCheck"
	FaceRecognitionService_Configure_FullMethodName       = "/orbo.recognition.v1.FaceRecognitionService/Configure"
)

// FaceRecognitionServiceClient is the client API for FaceRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FaceRecognitionService provides real-time face detection and recognition using InsightFace
type FaceRecognitionServiceClient interface {
	// RecognizeStream is a bidirectional streaming RPC for real-time face recognition
	// Client sends frames, server responds with face recognition results
	RecognizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FaceRequest, FaceResponse], error)
	// RegisterFace adds a new face identity to the database
	RegisterFace(ctx context.Context, in *RegisterFaceRequest, opts ...grpc.CallOption) (*RegisterFaceResponse, error)
	// DeleteFace removes a face identity from the database
	DeleteFace(ctx context.Context, in *DeleteFaceRequest, opts ...grpc.CallOption) (*DeleteFaceResponse, error)
	// ListFaces returns all registered face identities
	ListFaces(ctx context.Context, in *ListFacesRequest, opts ...grpc.CallOption) (*ListFacesResponse, error)
	// HealthCheck verifies the recognition service is operational
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Configure updates recognition parameters at runtime
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
}

type faceRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionServiceClient(cc grpc.ClientConnInterface) FaceRecognitionServiceClient {
	return &faceRecognitionServiceClient{cc}
}

func (c *faceRecognitionServiceClient) RecognizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FaceRequest, FaceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaceRecognitionService_ServiceDesc.Streams[0], FaceRecognitionService_RecognizeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FaceRequest, FaceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceRecognitionService_RecognizeStreamClient = grpc.BidiStreamingClient[FaceRequest, FaceResponse]

func (c *faceRecognitionServiceClient) RegisterFace(ctx context.Context, in *RegisterFaceRequest, opts ...grpc.CallOption) (*RegisterFaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFaceResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_RegisterFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) DeleteFace(ctx context.Context, in *DeleteFaceRequest, opts ...grpc.CallOption) (*DeleteFaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFaceResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_DeleteFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) ListFaces(ctx context.Context, in *ListFacesRequest, opts ...grpc.CallOption) (*ListFacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacesResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_ListFaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecognitionServiceServer is the server API for FaceRecognitionService service.
// All implementations must embed UnimplementedFaceRecognitionServiceServer
// for forward compatibility.
//
// FaceRecognitionService provides real-time face detection and recognition using InsightFace
type FaceRecognitionServiceServer interface {
	// RecognizeStream is a bidirectional streaming RPC for real-time face recognition
	// Client sends frames, server responds with face recognition results
	RecognizeStream(grpc.BidiStreamingServer[FaceRequest, FaceResponse]) error
	// RegisterFace adds a new face identity to the database
	RegisterFace(context.Context, *RegisterFaceRequest) (*RegisterFaceResponse, error)
	// DeleteFace removes a face identity from the database
	DeleteFace(context.Context, *DeleteFaceRequest) (*DeleteFaceResponse, error)
	// ListFaces returns all registered face identities
	ListFaces(context.Context, *ListFacesRequest) (*ListFacesResponse, error)
	// HealthCheck verifies the recognition service is operational
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// Configure updates recognition parameters at runtime
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

// UnimplementedFaceRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceRecognitionServiceServer struct{}

func (UnimplementedFaceRecognitionServiceServer) RecognizeStream(grpc.BidiStreamingServer[FaceRequest, FaceResponse]) error {
	return status.Error(codes.Unimplemented, "method RecognizeStream not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) RegisterFace(context.Context, *RegisterFaceRequest) (*RegisterFaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFace not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) DeleteFace(context.Context, *DeleteFaceRequest) (*DeleteFaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFace not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) ListFaces(context.Context, *ListFacesRequest) (*ListFacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFaces not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) mustEmbedUnimplementedFaceRecognitionServiceServer() {
}
func (UnimplementedFaceRecognitionServiceServer) testEmbeddedByValue() {}

// UnsafeFaceRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServiceServer will
// result in compilation errors.
type UnsafeFaceRecognitionServiceServer interface {
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

func RegisterFaceRecognitionServiceServer(s grpc.ServiceRegistrar, srv FaceRecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedFaceRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceRecognitionService_ServiceDesc, srv)
}

func _FaceRecognitionService_RecognizeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FaceRecognitionServiceServer).RecognizeStream(&grpc.GenericServerStream[FaceRequest, FaceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceRecognitionService_RecognizeStreamServer = grpc.BidiStreamingServer[FaceRequest, FaceResponse]

func _FaceRecognitionService_RegisterFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).RegisterFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_RegisterFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).RegisterFace(ctx, req.(*RegisterFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_DeleteFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).DeleteFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_DeleteFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).DeleteFace(ctx, req.(*DeleteFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_ListFaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).ListFaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_ListFaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).ListFaces(ctx, req.(*ListFacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceRecognitionService_ServiceDesc is the grpc.ServiceDesc for FaceRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbo.recognition.v1.FaceRecognitionService",
	HandlerType: (*FaceRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFace",
			Handler:    _FaceRecognitionService_RegisterFace_Handler,
		},
		{
			MethodName: "DeleteFace",
			Handler:    _FaceRecognitionService_DeleteFace_Handler,
		},
		{
			MethodName: "ListFaces",
			Handler:    _FaceRecognitionService_ListFaces_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FaceRecognitionService_HealthCheck_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _FaceRecognitionService_Configure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecognizeStream",
			Handler:       _FaceRecognitionService_RecognizeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/recognition/v1/recognition.proto",
}
